config/routes.rb
Rails.application.routes.draw do
  get 'homepages/index'

  resources :death_notices do
  member do
    get "vote"
  end
end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'homepages#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/death_notice.rb
class DeathNotice < ActiveRecord::Base
  belongs_to :user
  acts_as_votable 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  #->Prelang (user_login/devise)
  has_many :death_notices
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    # The User was found in our database
    return user if user

    # Check if the User is already registered without Facebook
    user = User.where(email: auth.info.email).first

    return user if user

    # The User was not found and we need to create them
    User.create(name:     auth.extra.raw_info.name,
                provider: auth.provider,
                uid:      auth.uid,
                email:    auth.info.email,
                password: Devise.friendly_token[0,20])
  end


  acts_as_votable 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  
  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/death_notices_controller.rb
class DeathNoticesController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_death_notice, only: [:show, :edit, :update, :destroy, :vote]

  # GET /death_notices
  # GET /death_notices.json
  def index
    @death_notices = DeathNotice.all
  end

  # GET /death_notices/1
  # GET /death_notices/1.json
  def show
  end

  # GET /death_notices/new
  def new
    @death_notice = DeathNotice.new
  end

  # GET /death_notices/1/edit
  def edit
  end

  # POST /death_notices
  # POST /death_notices.json
  def create
    @death_notice = DeathNotice.new(death_notice_params)
    @death_notice.user = current_user

    respond_to do |format|
      if @death_notice.save
        format.html { redirect_to @death_notice, notice: 'Death notice was successfully created.' }
        format.json { render :show, status: :created, location: @death_notice }
      else
        format.html { render :new }
        format.json { render json: @death_notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /death_notices/1
  # PATCH/PUT /death_notices/1.json
  def update
    respond_to do |format|
      if @death_notice.update(death_notice_params)
        format.html { redirect_to @death_notice, notice: 'Death notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @death_notice }
      else
        format.html { render :edit }
        format.json { render json: @death_notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /death_notices/1
  # DELETE /death_notices/1.json
  def destroy
    @death_notice.destroy
    respond_to do |format|
      format.html { redirect_to death_notices_url, notice: 'Death notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #->Prelang (voting/acts_as_votable)
  def vote

    direction = params[:direction]

    # Make sure we've specified a direction
    raise "No direction parameter specified to #vote action." unless direction

    # Make sure the direction is valid
    unless ["like", "bad"].member? direction
      raise "Direction '#{direction}' is not a valid direction for vote method."
    end

    @death_notice.vote_by voter: current_user, vote: direction

    redirect_to action: :index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_death_notice
      @death_notice = DeathNotice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def death_notice_params
      params.require(:death_notice).permit(:title, :date_added, :client_born, :client_died, :eulogy, :burial_date, :meeting_date, :burial_location, :meeting_location, :client_picture, :comments, :user_id)
    end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include ApplicationHelper

  def facebook

    # Attempt to find the User
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication # This will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      #session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def passthru
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  end

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/death_notices_helper.rb
module DeathNoticesHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/views/death_notices/_form.html.erb
<%= form_for @death_notice, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :title, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date_added, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :date_added, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :client_born, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :client_born, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :client_died, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :client_died, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :eulogy, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :eulogy, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :burial_date, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :burial_date, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :meeting_date, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :meeting_date, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :burial_location, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :burial_location, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :meeting_location, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :meeting_location, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :client_picture, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :client_picture, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :comments, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :comments, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  death_notices_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/death_notices/edit.html.erb
<%- model_class = DeathNotice -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => DeathNotice %></h1>
</div>
<%= render :partial => 'form' %>

app/views/death_notices/index.html.erb
<%- model_class = DeathNotice -%>
<div class="page-header">
  <h1><%=t '.title', :default => DeathNotice %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:date_added) %></th>
      <th><%= model_class.human_attribute_name(:client_born) %></th>
      <th><%= model_class.human_attribute_name(:client_died) %></th>
      <th><%= model_class.human_attribute_name(:eulogy) %></th>
      <th><%= model_class.human_attribute_name(:burial_date) %></th>
      <th><%= model_class.human_attribute_name(:meeting_date) %></th>
      <th><%= model_class.human_attribute_name(:burial_location) %></th>
      <th><%= model_class.human_attribute_name(:meeting_location) %></th>
      <th><%= model_class.human_attribute_name(:client_picture) %></th>
      <th><%= model_class.human_attribute_name(:comments) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @death_notices.each do |death_notice| %>
      <tr>
        <td><%= death_notice.id %></td>
        <td><%= death_notice.title %></td>
        <td><%= death_notice.date_added %></td>
        <td><%= death_notice.client_born %></td>
        <td><%= death_notice.client_died %></td>
        <td><%= death_notice.eulogy %></td>
        <td><%= death_notice.burial_date %></td>
        <td><%= death_notice.meeting_date %></td>
        <td><%= death_notice.burial_location %></td>
        <td><%= death_notice.meeting_location %></td>
        <td><%= death_notice.client_picture %></td>
        <td><%= death_notice.comments %></td>
        <td><%=l death_notice.created_at, format: :long %></td>
        <td>
          <%= link_to death_notice_path(death_notice), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to death_notice_path(death_notice), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_death_notice_path,
            :class => 'btn btn-primary' %>

app/views/death_notices/new.html.erb
<%- model_class = DeathNotice -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => DeathNotice %></h1>
</div>
<%= render :partial => 'form' %>

app/views/death_notices/show.html.erb
<%- model_class = DeathNotice -%>
<div class="page-header">
  <h1><%=t '.title', :default => DeathNotice %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:title) %></dt>
      <dd><pre class="prettyprint"><%= @death_notice.title %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:date_added) %></dt>
      <dd><pre class="prettyprint"><%= @death_notice.date_added %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:client_born) %></dt>
      <dd><pre class="prettyprint"><%= @death_notice.client_born %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:client_died) %></dt>
      <dd><pre class="prettyprint"><%= @death_notice.client_died %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:eulogy) %></dt>
      <dd><pre class="prettyprint"><%= @death_notice.eulogy %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:burial_date) %></dt>
      <dd><pre class="prettyprint"><%= @death_notice.burial_date %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:meeting_date) %></dt>
      <dd><pre class="prettyprint"><%= @death_notice.meeting_date %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:burial_location) %></dt>
      <dd><pre class="prettyprint"><%= @death_notice.burial_location %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:meeting_location) %></dt>
      <dd><pre class="prettyprint"><%= @death_notice.meeting_location %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:client_picture) %></dt>
      <dd><pre class="prettyprint"><%= @death_notice.client_picture %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:comments) %></dt>
      <dd><pre class="prettyprint"><%= @death_notice.comments %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              death_notices_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_death_notice_path(@death_notice), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              death_notice_path(@death_notice),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "My Application", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/homepages/index.html.erb
<h1>Homepages#index</h1>
<p>Find me in app/views/homepages/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KumbuRest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/><!-- Prelang: Analytics / Google Analytics -->
    <%= analytics_init if Rails.env.production? or Rails.env.development? %></head>
<body>
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>